//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string MORSE_CODE = "morse_code";
        
        public const string R_INDEXTIP = "r_indextip";
        
        public const string L_INDEXTIP = "l_indextip";
        
        public const string L_THUMBTIP = "l_thumbtip";
        
        public const string L_MIDDLETIP = "l_middletip";
        
        public const string L_RINGTIP = "l_ringtip";
        
        public const string L_PINKYTIP = "l_pinkytip";
        
        public const string R_THUMBTIP = "r_thumbtip";
        
        public const string R_MIDDLETIP = "r_middletip";
        
        public const string R_RINGTIP = "r_ringtip";
        
        public const string R_PINKYTIP = "r_pinkytip";
        
        public const string BUTTON_PRESS_RIGHT = "button_press_right";
        
        public const string BUTTON_PRESS_LEFT = "button_press_left";
        
        public const string DRAG_BLOCK_LEFT = "drag_block_left";
        
        public const string DRAG_BLOCK_RIGHT = "drag_block_right";
    }
}
